stages:
  - build
  - test
  - .post

build-job:       # Build stage: Compiles the code and packages it into a JAR
  stage: build
  script:
    - echo "Starting Maven build..."
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/  # Save build artifacts (e.g., JAR files) for use in later stages
  tags:
      - shell

unit-test-job:   # Test stage: Runs unit tests
  stage: test
  script:
    - echo "Running unit tests..."
    - mvn test
  artifacts:
    reports:
      junit: target/surefire-reports/*.xml  # Ensure JUnit test results are visible in GitLab
      coverage_report:
        coverage_format: jacoco
        path: target/site/jacoco.xml
  tags:
      - shell

lint-test-job:   # Test stage: Runs lint checks
  stage: test
  script:
    - echo "Checking code style..."
    - mvn spotless:check
  tags:
      - shell

cleanup:
  stage: .post
  script:
    - mvn clean
  tags:
      - shells
