@startuml

top to bottom direction
skinparam linetype ortho

class BiDirectionalMap<K, V> {
  + BiDirectionalMap(): 
  + getFromValue(V): K
  + put(K, V): void
  + removeByKey(K): void
  + removeByValue(V): void
  + getFromKey(K): V
}
class CommandLineOptions {
  - CommandLineOptions(): 
  - processOptions(CommandLine, Map<String, String>, HashMap<OptionType, String>): void
  - isFeatureImplemented(OptionType): boolean
  - loadDefaultArgs(String, HashMap<OptionType, String>): Map<String, String>
  - handleImmediateExitOptions(CommandLine, Options, Runtime): boolean
  + parseOptions(String[], Runtime): HashMap<OptionType, String>?
  + validateAiOptions(HashMap<OptionType, String>): void
  - handleLoggingOptions(CommandLine, Map<String, String>): void
}
class CustomFormatter {
  + CustomFormatter(): 
  + format(LogRecord): String
}
class IniParser {
  - IniParser(): 
  + parseIni(InputStream): Map<String, Map<String, String>>
}
class Logging {
  - Logging(): 
  + configureLogging(Logger): void
  + error(String): void
  + debug(Logger, String): void
  + verbose(Logger, String): void
  + print(String): void
   verbose: boolean
   debug: boolean
}
class MoveHistoryParser {
  - MoveHistoryParser(): 
  + parseHistoryFile(InputStream): List<String>
  - parseMoves(String): List<String>
}
enum OptionType << enumeration >> {
  + OptionType(): 
  + valueOf(String): OptionType
  + values(): OptionType[]
   short: String
   long: String
   option: Option
}
entity Position << record >> {
  + Position(int, int): 
  + y(): int
  + equals(Object): boolean
  + x(): int
  + toString(): String
   copy: Position
   valid: boolean
}
class TextGetter {
  - TextGetter(): 
  - locale: Locale
  + getText(String, Object[]): String
  + getText(String): String
   locale: Locale
}
class Timer {
  + Timer(long): 
  + Timer(long, Runnable): 
  + start(): void
  + stop(): void
  + run(): void
   timeRemaining: long
   timeRemainingString: String
   callback: Runnable
}

CommandLineOptions  -[#595959,dashed]->  OptionType         : "«create»"
Logging             -[#595959,dashed]->  CustomFormatter    : "«create»"
@enduml
