@startgantt
Project starts 2025-01-08
[Project presentation] requires 8 days
[Preliminary report] requires 16 days 
[Preliminary report] starts at [Project presentation]'s end
[Project development] requires 8 weeks
[Project development] starts at [Preliminary report]'s end
[Final presentation] requires 1 day
[Final presentation] starts at 2025-04-03
-- During all the project --
[F1 Programming language] as [F1] requires 8 weeks
[Preliminary report] -> [F1]
[F2 Coding style] as [F2] requires 8 weeks
[Preliminary report] -> [F2]
[F3 Default language in code, documentation, ...] as [F3] requires 8 weeks
[Preliminary report] -> [F3]
[F4 Operating System] as [F4] requires 8 weeks
[Preliminary report] -> [F4]
[F5 documentation] as [F5] requires 8 weeks
[Preliminary report] -> [F5]
[F6 Tests] as [F6] requires 8 weeks
[Preliminary report] -> [F6]
[F7 Bugs] as [F7] requires 8 weeks
[Preliminary report] -> [F7]
[F8 Measure performances] as [F8] requires 8 weeks
[Preliminary report] -> [F8]
[F9 Build system] as [F9] requires 8 weeks
[Preliminary report] -> [F9]
[F10 Test framework] as [F10] requires 8 weeks
[Preliminary report] -> [F10]
[F13 Internationalisation] as [F13] requires 8 weeks
[Preliminary report] -> [F13]
[F14 Binary name] as [F14] requires 8 weeks
[Preliminary report] -> [F14]
[F15 General usage] as [F15] requires 8 weeks
[Preliminary report] -> [F15]

-- 1st module (Game and CLI) --
[F11 Options managment] as [F11] requires 1 day and starts at [Preliminary report]'s end
[F16 CLI help] requires 1 day and starts at [F11]'s end
[F17 Version] requires 1 day and starts at [F11]'s end
[F18 Verbose Mode] requires 1 day and starts at [F11]'s end
[F19 Debug mode] requires 1 day and starts at [F11]'s end
[F13 Internationalisation setup] requires 1 day and starts at [Preliminary report]'s end

[F44 BitBoard module] as [F44] requires 2 days and starts at [Preliminary report]'s end
[F43 Game Board] as [F43] requires 2 days and starts at [F44]'s end
[F45 Game State] as [F45] requires 2 days and starts at [F43]'s end
[Rules] requires 1 week and starts at [F45]'s end
[F29 En-passant] as [F29] requires 1 day and starts at [Rules]'s start
[F30 Castling] as [F30] requires 1 day and starts at [Rules]'s start
[F31 Promotion] as [F31] requires 1 day and starts at [Rules]'s start
[F38 End of the game] as [F38] requires 3 days and starts at [Rules]'s start

[F24 CLI game] as [F24] requires 1 week and starts at [F45]'s end
[F26 Board display] as [F26] requires 1 day and starts at [F24]'s start
[F27 Moves syntax] as [F27] requires 1 day and starts at [F24]'s start
[F28 Historic] as [F28] requires 1 day and starts at [F27]'s end
[F33 Display messages] as [F33] requires 1 day and starts at [F24]'s start

2025-01-30 to 2025-02-13 are colored in LightPink
2025-02-14 to 2025-02-27 are colored in PeachPuff
2025-02-28 to 2025-03-13 are colored in TECHNOLOGY
2025-03-14 to 2025-03-27 are colored in LightSkyBlue
@endgantt

